const express = require('express');
const router = express.Router();
const urlController = require('../controllers/urlController.js');
router.post('/', urlController.generate);
router.get('/', (req, res) => res.send("URL Shortener Backend is working ✅"));
router.get('/stats', urlController.getStats);
router.get('/getreviews', urlController.getReviews);
router.get('/:shortUrl', urlController.redirect);
router.post('/getshorturl', urlController.getShortUrl);
router.post('/review', urlController.submitReview);
module.exports = router;
